# Generated by Django 3.1.4 on 2021-01-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0001_initial'),
        ('saidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidas',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Insira o item de saida', null=True, on_delete=django.db.models.deletion.PROTECT, to='pecas.pecas', verbose_name='Item de saida:'),
        ),
        migrations.AddField(
            model_name='saidas',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='N° de cliques', max_digits=10, null=True, verbose_name='N° de edições:'),
        ),
    ]
