# Generated by Django 3.1.4 on 2021-01-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
        ('saidas', '0003_auto_20210107_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidas',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Insira a unidade', null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidade', verbose_name='Unidade:'),
        ),
    ]
