# Generated by Django 3.1.4 on 2021-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20210107_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Valor do item:'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Quantidade do item:'),
        ),
    ]
