# Generated by Django 3.1.4 on 2021-01-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20210115_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Valor total do item:'),
        ),
    ]
