# Generated by Django 3.1.4 on 2021-01-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
        ('compras', '0002_auto_20210107_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Insira a unidade', null=True, on_delete=django.db.models.deletion.PROTECT, to='unidades.unidade', verbose_name='Unidade:'),
        ),
    ]
