# Generated by Django 3.1.4 on 2021-01-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Insira o cliente', null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.clientes', verbose_name='Cliente:'),
        ),
    ]
